/**
 * The theme kit: everything a capture decided, as files for someone's own site.
 *
 * The live page uses self-hosted fonts behind next/font variables and blob URLs
 * for the photo texture — neither exists anywhere else. The kit rewrites fonts
 * as Google Fonts family names with a matching `@import`, drops the
 * runtime-only photo variables, and emits the same values three ways: plain CSS
 * custom properties, a Tailwind v4 `@theme` block, and W3C design tokens.
 *
 * Pure: strings in, strings out. Zipping and downloading happen in the browser.
 */

import { contrastHex } from './color';
import { FONT_FAMILIES, FontKey, PAIRING_BY_ID, googleFontsUrl } from './fonts';
import { describeMood } from './synthesize';
import { DesignTokens, tokenVariables } from './tokens';

export interface KitFile {
  name: string;
  content: string;
}

/** A font-family value with a real family name, for use outside this app. */
function portableStack(key: FontKey): string {
  const f = FONT_FAMILIES[key];
  return `'${f.name}', ${f.fallback}`;
}

/** Custom properties as they should appear in someone else's stylesheet. */
export function portableVariables(tokens: DesignTokens): Array<[string, string]> {
  const pairing = PAIRING_BY_ID.get(tokens.typography.pairing);
  const fonts: Record<string, string> = pairing
    ? {
        '--font-heading': portableStack(pairing.heading),
        '--font-body': portableStack(pairing.body),
        '--font-accent': portableStack(pairing.accent),
      }
    : {};
  return tokenVariables(tokens).map(([name, value]) => [name, fonts[name] ?? value]);
}

export function slug(text: string): string {
  return (
    text
      .toLowerCase()
      .normalize('NFKD')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 40) || 'textures'
  );
}

const fontImport = (tokens: DesignTokens) => {
  const pairing = PAIRING_BY_ID.get(tokens.typography.pairing);
  return pairing ? `@import url('${googleFontsUrl(pairing)}');\n\n` : '';
};

function header(tokens: DesignTokens): string {
  return `/*
 * ${tokens.copy.brand} — generated by Textures
 * ${describeMood(tokens.mood)}
 * Layout: ${tokens.layout.archetype} · Type: ${tokens.typography.label} · Palette: ${tokens.palette.strategy}
 */

`;
}

/** Plain CSS: variables on :root plus a small, readable starter layer. */
export function themeCss(tokens: DesignTokens): string {
  const vars = portableVariables(tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  const scheme = tokens.meta.sourceIsDark ? 'dark' : 'light';

  return `${fontImport(tokens)}${header(tokens)}:root {
${vars}
  color-scheme: ${scheme};
}

body {
  background-color: var(--color-surface);
  color: var(--color-ink);
  font-family: var(--font-body);
  font-weight: var(--weight-body);
  line-height: var(--leading-body);
}

h1,
h2,
h3 {
  font-family: var(--font-heading);
  font-weight: var(--weight-heading);
  letter-spacing: var(--tracking-heading);
  text-transform: var(--heading-case);
  line-height: 1.05;
}

h1 {
  font-size: calc(clamp(2.4rem, 7vw, 5.5rem) * var(--type-scale));
}

em {
  font-style: var(--heading-style);
  color: var(--color-accent);
}

p {
  max-width: var(--measure);
}

.muted {
  color: var(--color-ink-muted);
}

.button {
  display: inline-flex;
  align-items: center;
  padding: calc(var(--spacing) * 3) calc(var(--spacing) * 6);
  border-radius: var(--radius-md);
  background: var(--color-primary);
  color: var(--color-on-primary);
  font-weight: 600;
}

.card {
  padding: calc(var(--spacing) * 6);
  border: 1px solid var(--color-line);
  border-radius: var(--radius-lg);
  background: var(--color-surface-alt);
  box-shadow: var(--shadow-elevated);
}

.grain::after {
  content: '';
  position: fixed;
  inset: 0;
  pointer-events: none;
  background-image: var(--grain-image);
  opacity: var(--grain-opacity);
  mix-blend-mode: overlay;
}
`;
}

/**
 * Tailwind v4: the variables inside `@theme`, so `bg-primary`, `text-ink`,
 * `font-heading`, `rounded-lg` and the spacing scale all follow the kit.
 */
export function tailwindTheme(tokens: DesignTokens): string {
  const themed = portableVariables(tokens).filter(([k]) =>
    /^--(color|font|radius|tracking|leading|spacing|shadow|blur)-?/.test(k),
  );
  const rest = portableVariables(tokens).filter(([k]) => !themed.some(([t]) => t === k));
  const block = (pairs: Array<[string, string]>) => pairs.map(([k, v]) => `  ${k}: ${v};`).join('\n');

  return `${fontImport(tokens)}@import 'tailwindcss';

${header(tokens)}@theme {
${block(themed)}
}

/* Not a Tailwind namespace — read with arbitrary values, e.g. max-w-(--measure). */
:root {
${block(rest)}
}
`;
}

/** W3C Design Tokens (DTCG) format, for Figma plugins, Style Dictionary and friends. */
export function designTokens(tokens: DesignTokens): string {
  const { palette, typography, radius, surface, space, motion } = tokens;
  const pairing = PAIRING_BY_ID.get(typography.pairing);
  const family = (key: FontKey | undefined, fallback: string) =>
    key ? [FONT_FAMILIES[key].name, ...FONT_FAMILIES[key].fallback.split(',').map((s) => s.trim())] : [fallback];

  const color = (value: string, description?: string) => ({
    $type: 'color',
    $value: value,
    ...(description ? { $description: description } : {}),
  });

  const doc = {
    $description: `${tokens.copy.brand} — ${describeMood(tokens.mood)}. Generated by Textures.`,
    color: {
      primary: color(palette.primary),
      onPrimary: color(palette.onPrimary, 'Text on primary; at least 4.5:1'),
      secondary: color(palette.secondary),
      accent: color(palette.accent, 'At least 3:1 on surface'),
      surface: color(palette.surface),
      surfaceAlt: color(palette.surfaceAlt),
      ink: color(palette.ink, 'Body text; at least 7:1 on surface'),
      inkMuted: color(palette.inkMuted, 'Secondary text; at least 4.5:1 on surface'),
      line: color(palette.border),
      ...Object.fromEntries(
        palette.pops.flatMap((pop, i) => [
          [`pop${i + 1}`, color(pop.color)],
          [`onPop${i + 1}`, color(pop.on)],
        ]),
      ),
    },
    font: {
      heading: { $type: 'fontFamily', $value: family(pairing?.heading, 'sans-serif') },
      body: { $type: 'fontFamily', $value: family(pairing?.body, 'sans-serif') },
      accent: { $type: 'fontFamily', $value: family(pairing?.accent, 'sans-serif') },
    },
    fontWeight: {
      heading: { $type: 'fontWeight', $value: typography.headingWeight },
      body: { $type: 'fontWeight', $value: typography.bodyWeight },
    },
    letterSpacing: { heading: { $type: 'dimension', $value: `${typography.tracking}em` } },
    lineHeight: { body: { $type: 'number', $value: typography.leading } },
    radius: {
      sm: { $type: 'dimension', $value: radius.sm },
      md: { $type: 'dimension', $value: radius.md },
      lg: { $type: 'dimension', $value: radius.lg },
      xl: { $type: 'dimension', $value: radius.xl },
    },
    spacing: { unit: { $type: 'dimension', $value: `${(0.25 * space.unit).toFixed(4)}rem` } },
    shadow: { elevated: { $type: 'string', $value: surface.shadow } },
    duration: { motion: { $type: 'duration', $value: `${motion.period}ms` } },
    $extensions: {
      'textures.mood': tokens.mood,
      'textures.layout': tokens.layout,
      'textures.motion': motion,
      'textures.finish': surface.finish,
      'textures.palette.strategy': palette.strategy,
      'textures.palette.weights': palette.weights,
    },
  };
  return JSON.stringify(doc, null, 2) + '\n';
}

export function readme(tokens: DesignTokens): string {
  const { palette, typography, layout, copy } = tokens;
  const ratio = (a: string, b: string) => contrastHex(a, b).toFixed(2);
  const swatch = (name: string, hex: string) => `| ${name} | \`${hex}\` |`;
  const pairing = PAIRING_BY_ID.get(typography.pairing);

  return `# ${copy.brand} — theme kit

Generated by Textures from a photograph read as **${describeMood(tokens.mood)}**.

- **Layout archetype:** ${layout.archetype} (hero: ${layout.sections.hero}, features: ${layout.sections.features}, interlude: ${layout.sections.interlude}, closing: ${layout.sections.cta})
- **Type:** ${typography.label}${pairing ? ` — ${pairing.description}` : ''}${typography.uppercase ? ' (uppercase headings)' : ''}
- **Palette:** ${palette.strategy} · ${tokens.meta.sourceIsDark ? 'dark' : 'light'} scheme
- **Finish:** ${tokens.surface.finish} · **Motion:** ${tokens.motion.character} (${tokens.motion.tier})

## Files

| File | Use it when |
| --- | --- |
| \`theme.css\` | Any site. Link it, then use \`var(--color-primary)\` and friends; it includes a small starter layer (\`body\`, headings, \`.button\`, \`.card\`, \`.grain\`). |
| \`tailwind-theme.css\` | A Tailwind v4 project. Use it as your main stylesheet; \`bg-primary\`, \`text-ink\`, \`font-heading\` and \`rounded-lg\` follow the kit. |
| \`tokens.json\` | Design tools. W3C Design Tokens format, readable by Style Dictionary, Tokens Studio and similar. |

Fonts load from Google Fonts via the \`@import\` at the top of both CSS files.

## Palette

| Role | Value |
| --- | --- |
${[
  swatch('primary', palette.primary),
  swatch('on-primary', palette.onPrimary),
  swatch('secondary', palette.secondary),
  swatch('accent', palette.accent),
  swatch('surface', palette.surface),
  swatch('surface-alt', palette.surfaceAlt),
  swatch('ink', palette.ink),
  swatch('ink-muted', palette.inkMuted),
  swatch('line', palette.border),
  ...palette.pops.map((p, i) => swatch(`pop-${i + 1} / on-pop-${i + 1}`, `${p.color} / ${p.on}`)),
].join('\n')}

## Contrast

| Pair | Ratio | Target |
| --- | --- | --- |
| ink on surface | ${ratio(palette.ink, palette.surface)} | 7 |
| ink-muted on surface | ${ratio(palette.inkMuted, palette.surface)} | 4.5 |
| on-primary on primary | ${ratio(palette.onPrimary, palette.primary)} | 4.5 |
| accent on surface | ${ratio(palette.accent, palette.surface)} | 3 (large text and UI) |
`;
}

export function themeKit(tokens: DesignTokens): KitFile[] {
  return [
    { name: 'theme.css', content: themeCss(tokens) },
    { name: 'tailwind-theme.css', content: tailwindTheme(tokens) },
    { name: 'tokens.json', content: designTokens(tokens) },
    { name: 'README.md', content: readme(tokens) },
  ];
}
